clientId: D9DO4l9IhLT5jRdhiQXXcA2q
spring:
  application:
    name: huangxj-base
  profiles:
    active: @profile.name@
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:attachment
server:
  compression:
    enabled: true
  http2:
    enabled: true

# mybatis
mybatis-plus:
  mapper-locations[0]: classpath:com/huangxj/base/system/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.huangxj.base.**.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    #刷新mapper 调试神器
    refresh: true
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#配置日志地址
logging:
  config: classpath:logback.xml


