#服务器端口
server:
  port: 8090

spring:
  shardingsphere:
    # 定义数据源
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://111.230.227.215:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: yct@_603

#base_url: https://sgrh.huangxj.net

#腾讯云短信
sms.appid: 1400208603
sms.appkey: 8961a67952d4db2a111bd120d3bb378e

#小程序
#wx:
#  miniapp:
#    configs:
#      - appid:
#        secret:
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
#        msgDataFormat: JSON