#服务器端口
server:
  port: 8300


  #数据源配置
#  datasource:
#    url: jdbc:mysql://192.168.2.249:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
spring:
  shardingsphere:
    # 定义数据源
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.107.101.62:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
#    props:
#      # 用密文查询
#      query.with.cipher.column: true
#    encrypt:
#      encryptors:
#        encryptor-aes:
#          type: aes
#          props:
#            aes.key.value: 123456
#      tables:
#        sys_user:
#          columns:
#            # 明文字段，用于查询的字段
#            mobile:
#              encryptor: encryptor-aes
#              cipherColumn: mobile

#base_url: http://www.huangxj.net:20020

#sms.appid:
#sms.appkey:

#wx:
#  miniapp:
#    enabled: true
#    configs:
#      - appid:
#        secret:
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
#        msgDataFormat: JSON
